# Generated by Django 4.2.4 on 2023-08-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0002_calculator_income_calculator_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='car',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='finance',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='house',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='imcome_fam',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='income_myself',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='land',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='marry',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='property',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='rental_deposit',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='welfare',
        ),
    ]
