# Generated by Django 4.2.4 on 2023-08-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='tag',
            new_name='tags',
        ),
    ]
