# Generated by Django 4.2.4 on 2023-08-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_rename_tag_community_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='tags',
            field=models.CharField(max_length=20),
        ),
    ]
