# Generated by Django 4.2.4 on 2023-08-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='section',
            field=models.CharField(default='1구간', max_length=10, verbose_name='구간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='tags',
            field=models.CharField(max_length=20, verbose_name='태그'),
        ),
    ]
