# Generated by Django 4.2.4 on 2023-08-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_community_section_alter_community_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='구간'),
        ),
    ]
