# Generated by Django 4.2.4 on 2023-08-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_alter_community_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='파일'),
        ),
    ]
