# Generated by Django 4.2.4 on 2023-08-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tongtong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/')),
                ('tag', models.TextField(verbose_name='태그')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
