# Generated by Django 4.2.4 on 2023-08-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tongtong', '0003_rename_image_uploadedbenefit_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('tag', models.TextField(verbose_name='태그')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedBenefit',
        ),
    ]
