# Generated by Django 4.2.4 on 2023-08-14 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tongtong', '0004_uploadimage_delete_uploadedbenefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
