# Generated by Django 4.2.4 on 2023-08-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tongtong', '0005_counter_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='count',
            new_name='counts',
        ),
    ]
